### ISSUE TITLE
Upgrade faraday dependency

### ISSUE THREAD

**Issue by sudall** [amcaplan/simple_jsonapi_client#24]
Any chance the faraday dependency could get an upgrade? I'm trying to use sentry-ruby, but it depends on faraday >= 1 (https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/sentry-ruby.gemspec), so it's conflicting with the ~> 0.12 dependency of this gem.

**Comment by amcaplan** [comment]
Looking at https://github.com/lostisland/faraday/blob/master/CHANGELOG.md it seems that there aren't any breaking changes in faraday 1.0, so let's try and make this happen!

I've been pushing off gem updates due to some difficulty with bundler and travis, but maybe it'll be easier now?

**Comment by amcaplan** [comment]
I'm so sorry @sudall, I thought I had pushed an update a while back, looks like I never merged due to CI issues.

Well, I didn't solve the CI issues, but I know it worked locally, so I figure let's merge now, and figure out out later. So I merged and published 0.2.5, hope it works for you!

By the way, in the future, please don't hesitate to bump the issue (respectfully) if it's urgent, I might have just forgotten.

**Comment by sudall** [comment]
No worries! thank you very much for doing this!
